# Generated by Django 3.1 on 2020-08-16 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrito', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrito',
            name='cantidad',
            field=models.IntegerField(default=0),
        ),
    ]
