# Generated by Django 3.1 on 2020-08-19 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrito', '0002_carrito_cantidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrito',
            name='precio_unidad',
            field=models.DecimalField(blank=True, decimal_places=0, default=None, max_digits=19, null=True),
        ),
    ]
