# Generated by Django 3.1 on 2020-08-19 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrito', '0003_carrito_precio_unidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrito',
            name='precio_unidad',
            field=models.IntegerField(),
        ),
    ]
