# Generated by Django 3.1 on 2020-08-15 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='precio_unidad',
            field=models.DecimalField(blank=True, decimal_places=0, default=None, max_digits=19, null=True),
        ),
    ]
